### ISSUE TITLE
Checksums in the .yml don't match

### ISSUE THREAD

**Issue by PicoJr** [upscayl/upscayl#289]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

Hello, I downloaded the latest AppImage from here <https://github.com/upscayl/upscayl/releases/download/v2.0.1/upscayl-2.0.1-linux.AppImage> (twice, to check it wasn't a network issue), and upon checking its sha512sum it does not match the one provided in <https://github.com/upscayl/upscayl/releases/download/v2.0.1/latest-linux.yml>:

```
❯ sha512sum upscayl-2.0.1-linux.AppImage
9c76fc4e02374d91c904db3f0084338b908c1d88a7282ea9fc6be82de6a23578a6c040edd98703fb5437f729c614d6b71ba59c27a372bfc54a398372ef8a1a25  upscayl-2.0.1-linux.AppImage
```

vs

```
version: 2.0.1
files:
  - url: upscayl-2.0.1-linux.AppImage
    sha512: nHb8TgI3TZHJBNs/AIQzi5CMHYinKC6p/GvoLeaiNXimwEDt2YcD+1Q39ynGFNa3G6WcJ6Nyv8VKOYNy74oaJQ==
    size: 337745575
    blockMapSize: 353979
path: upscayl-2.0.1-linux.AppImage
sha512: nHb8TgI3TZHJBNs/AIQzi5CMHYinKC6p/GvoLeaiNXimwEDt2YcD+1Q39ynGFNa3G6WcJ6Nyv8VKOYNy74oaJQ==
releaseDate: '2022-12-27T11:44:43.731Z'
```

Same for the windows exe:

```
❯ sha512sum upscayl-2.0.1-win.exe 
828bebe5827bdeb5c0d50f445d2a3b9beee54c0b7689019f2e5ea5f5340203212acd828d08dce758fc4cc87113936fabff83310dfcd9185c7a115bba7faa02d7  upscayl-2.0.1-win.exe
```

vs

```
version: 2.0.1
files:
  - url: upscayl-2.0.1-win.exe
    sha512: govr5YJ73rXA1Q9EXSo7m+7lTAt2iQGfLl6l9TQCAyEqzYKNCNznWPxMyHETk2+r/4MxDfzZGFx6EVu6f6oC1w==
    size: 314258468
path: upscayl-2.0.1-win.exe
sha512: govr5YJ73rXA1Q9EXSo7m+7lTAt2iQGfLl6l9TQCAyEqzYKNCNznWPxMyHETk2+r/4MxDfzZGFx6EVu6f6oC1w==
releaseDate: '2022-12-27T11:39:19.877Z'
```

Maybe I am missing something obvious ?

Best regards,

### Expected Behavior

I would expect the checksum of the AppImage to match the one inside the `latest-linux.yml`.

### Screenshots

No screenshot.
